"""release 2025-08-27

Revision ID: 4964a1e9b078
Revises: c2c8af529b1b
Create Date: 2025-08-27 11:53:27.389527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4964a1e9b078'
down_revision: Union[str, Sequence[str], None] = 'c2c8af529b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('discounted_unit_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_discounts_id'), 'bulk_discounts', ['id'], unique=False)
    op.alter_column('purchase_order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_purchase_order_items_order_id'), 'purchase_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_product_id'), 'purchase_order_items', ['product_id'], unique=False)
    op.add_column('purchase_orders', sa.Column('shipping_cost', sa.Float(), nullable=False))
    op.add_column('purchase_orders', sa.Column('handling_cost', sa.Float(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_created_at'), 'purchase_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_orders_user_id'), 'purchase_orders', ['user_id'], unique=False)
    op.add_column('sales', sa.Column('payment_type', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('processing_fee', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('credit_card_fee_percent', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('users', sa.Column('credit_card_fee_flat', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credit_card_fee_flat')
    op.drop_column('users', 'credit_card_fee_percent')
    op.drop_column('sales', 'processing_fee')
    op.drop_column('sales', 'payment_type')
    op.drop_index(op.f('ix_purchase_orders_user_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_at'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'handling_cost')
    op.drop_column('purchase_orders', 'shipping_cost')
    op.drop_index(op.f('ix_purchase_order_items_product_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_order_id'), table_name='purchase_order_items')
    op.alter_column('purchase_order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_bulk_discounts_id'), table_name='bulk_discounts')
    op.drop_table('bulk_discounts')
    # ### end Alembic commands ###
